### ISSUE TITLE
can munin::node implement a "plugin purge" or whitelist?

### ISSUE THREAD

**Issue by neoice** [ssm/ssm-munin#28]
on most distros, the munin package automatically symlinks dozens of plugins into /etc/munin/plugins. I would like to enforce that **only** Puppet-managed plugins are running. it might be possible to use `ensure => absent` but you might wind up with resource conflicts later if you want to `ensure => present` on a subset of your fleet. from an enduser perspective, I'd love to say:

```
munin::node {
  purge_unmanaged_plugins => true,
}
```

or similar (maybe use a shorter param name)

I honestly have no better ideas. I've thought about this problem a few times while maintaining an in-house munin module over the past few years, but I've never made progress on it.

**Comment by ssm** [comment]
That's a good idea.

Having the module purge unmaintained plugins and plugin configuration with a set of parameters (default to false) would be a good improvement.

I'll add this to the munin module.

In the meanwhile, you can make a future proof workaround with:

    if ! defined(File['/etc/munin/plugins']) {
      file { '/etc/munin/plugins':
        ensure  => directory,
        recurse => true,
        purge   => true,
      }
    }
    else {
      notice('I can remove my workaround')
    }

**Comment by neoice** [comment]
![slowclap.gif](http://i.imgur.com/ttzaQXQ.gif)

I'm so excited that you provided a workaround. I'm patient and I've seen the `if !defined` idiom lead to bizarro behavior if not used carefully, so I probably won't deploy it... but I wish more devs were as considerate as you!
