### ISSUE TITLE
Module should not cause warnings when used without puppetdb/storeconfig

### ISSUE THREAD

**Issue by tohuwabohu** [ssm/ssm-munin#30]
I'm not using puppetdb/storeconfigs. But even though I've disabled the export on master and host, I still get warnings like

```
==> default: Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 127 in file /vagrant/environments/production/modules/munin/manifests/master.pp
==> default: Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 131 in file /vagrant/environments/production/modules/munin/manifests/master.pp
==> default: Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 136 in file /vagrant/environments/production/modules/munin/manifests/master.pp
==> default: Warning: You cannot collect without storeconfigs being set on line 121 in file /vagrant/environments/production/modules/munin/manifests/node.pp
```

This is not a blocker but not nice and makes it easy to miss other warnings or errors. It looks like regardless of the setting, Puppet will always evaluate the expressions even though the exports are not actually executed.

Perhaps a similar solution like for the [saz/ssh module](https://github.com/saz/puppet-ssh/issues/24) would work here as well: the exports are moved into a separate manifest that is not included when the export is disabled ...

btw: good work on the module!

**Comment by ssm** [comment]
tohuwabohu <notifications@github.com> writes:

> Perhaps a similar solution like for the [saz/ssh
> module](https://github.com/saz/puppet-ssh/issues/24) would work here
> as well: the exports are moved into a separate manifest that is not
> included when the export is disabled ...

That looks like a pattern which would work well.  Thanks for the link.

> btw: good work on the module!

Thank you. :)

-- 
Stig Sandbeck Mathisen

**Comment by tohuwabohu** [comment]
:+1:
