### ISSUE TITLE
Missing test instructions

### ISSUE THREAD

**Issue by l0b0** [ssm/ssm-munin#41]
As someone not familiar with `Guardfile` and `Rakefile`, it would be nice to have instructions to run tests. Assuming it works like `make`, I just get the following:

    $ rake
    rake aborted!
    LoadError: cannot load such file -- puppetlabs_spec_helper/rake_tasks
    /home/user/dev/ssm-munin/Rakefile:1:in `<top (required)>'
    (See full trace by running task with --trace)

**Comment by ssm** [comment]
I've added a CONTRIBUTING.md file to address this.
