### ISSUE TITLE
Unknown variable: 'plugin_target'

### ISSUE THREAD

**Issue by triforce** [ssm/ssm-munin#43]
I am getting this warning in my puppetserver log:

Puppet Unknown variable: 'plugin_target'. at /etc/puppetlabs/code/environments/development/modules/munin/manifests/plugin.pp:80:23

I have just upgraded to puppet 4 from puppet 3.7.2. Before the upgrade this warning message was not appearing.

I presume puppet 4 is slightly stricter with syntax?

Will this cause any problems?

Many thanks.

**Comment by ssm** [comment]
It is so far only a warning about an unset variable.

With puppet 4 it warns by default, but with 5, it will stop compilation, so I better fix variable initialization properly before that.

Thanks for reporting it.

**Comment by danielpo** [comment]
Hi! 
Can this be fixed? Puppet 5 is stable now.

**Comment by ssm** [comment]
This should be fixed in the 0.2.0 release
