### ISSUE TITLE
Munin-Nodes complain that Net::CIDR isn't installed

### ISSUE THREAD

**Issue by mrmikeace** [ssm/ssm-munin#58]
A minor issue that could be solved by installing the perl module, or also with this easy workaround - instead of defining munin::node allow to be a CIDR block, you can define it to be a regular expression. For example, say you want to allow anything in 10.0.0.0/8, change:
    allow          => [ '10.0.0.0/8' ],
to:
    allow          => [ ^10\..*$ ],

**Comment by ssm** [comment]
I must admit that I have not tested that the dependency is installed on all platforms.

On Debian GNU/Linux 9 (stretch), Net::CIDR is installed through dependencies munin-node -> libnet-server-perl -> libnet-cidr-perl

On CentOS 7, perl-Net-CIDR is not on the dependencies list for munin-node, and must be installed manually.

Do you use another distribution or operating system?

**Comment by ssm** [comment]
A way to fix this is to allow the package parameter to accept both string and array, and set the packages for munin-node on the Red Hat OS family to include perl-Net-CIDR.  I'll add this to the next release.

**Comment by ssm** [comment]
On CentOS-8, "dnf install munin munin-node" now installs the perl-Net-CIDR package.
