### ISSUE TITLE
PUppet deleted all my nodes.cnf

### ISSUE THREAD

**Issue by augustocarvalho** [ssm/ssm-munin#65]
After the changes on 12th Oct all my nodes configuration were gone from /etc/munin/munin-conf.d/
I was using the Master Branch to deploy the plugin on puppet4.

**Comment by ssm** [comment]
Augusto Carvalho <notifications@github.com> writes:

> After the changes on 12th Oct all my nodes configuration were gone
> from /etc/munin/munin-conf.d/

Hello. Thanks for reporting a bug.

If I could trouble you for some more information:

- Which version of puppet are you running?

- Are the munin nodes exported to PuppetDB, and then collected on the
  munin master?

I'm refactoring the module to support newer puppet versions as I have
spare time, so it would probably be safer to stick with a tagged version
of the module for now.

-- 
Stig Sandbeck Mathisen
