### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [ssm/ssm-munin#66]
Hi,
I noticed that the last release was quite some time ago. Could you do a new release to bring all changes in master to a release?

**Comment by ssm** [comment]
Hello bastelfreak,

I'll run tests, and make a new release as soon as I am fairly confident I don't break too much.

**Comment by ssm** [comment]
Hello,

The 0.3.0 release is now uploaded to Puppet forge.  Thanks for the reminder. :)
