### ISSUE TITLE
munin master not collecting nodes when using "munin::master::collect_nodes: mine"

### ISSUE THREAD

**Issue by mgeerdsen** [ssm/ssm-munin#70]
**Expected behavior**

When setting `munin::master::collect_nodes: 'mine'` those exported nodes should be collected for which the mastername is set accordingly. This worked in 0.0.1 e.g.

**Current behavior**

No nodes are currently collected when including the class `munin::master` and setting `collect_nodes` to anything but `enabled`

The reason lies in https://github.com/ssm/ssm-munin/blob/main/manifests/master.pp#L159
where `munin::master::collect` is only included when `collect_nodes` is set to `enabled`. In older version this was checking
```
$collect_nodes != 'disabled'
```

**Comment by ssm** [comment]
Fixed in 0.5.0
